// 토익 단어 마스터 플랜 단어 데이터
// day: 일차, w: 단어, pos: 품사, ko: 뜻, ex: 예문(단어 원형 그대로 포함), exKo: 예문 해석
// 새 일차를 추가할 때는 이 배열 맨 아래에 이어서 붙이면 됩니다.
const WORDS = [
  // ── Day 1 · 채용·지원 (기본 50) ──
  { day: 1, w: "applicant", pos: "n.", ko: "지원자", ex: "Each applicant must submit two references.", exKo: "각 지원자는 추천서 두 부를 제출해야 한다." },
  { day: 1, w: "application", pos: "n.", ko: "지원(서), 신청", ex: "Please fill out the application form by Friday.", exKo: "금요일까지 지원서를 작성해 주세요." },
  { day: 1, w: "apply", pos: "v.", ko: "지원하다, 신청하다", ex: "She decided to apply for the marketing position.", exKo: "그녀는 마케팅 직에 지원하기로 했다." },
  { day: 1, w: "appoint", pos: "v.", ko: "임명하다", ex: "The board will appoint a new director next month.", exKo: "이사회는 다음 달 새 이사를 임명할 것이다." },
  { day: 1, w: "attach", pos: "v.", ko: "첨부하다", ex: "Please attach your resume to the email.", exKo: "이메일에 이력서를 첨부해 주세요." },
  { day: 1, w: "benefit", pos: "n.", ko: "혜택, 복리후생", ex: "The company offers a generous benefit package.", exKo: "회사는 넉넉한 복리후생 제도를 제공한다." },
  { day: 1, w: "candidate", pos: "n.", ko: "후보자, 지원자", ex: "The ideal candidate will have sales experience.", exKo: "이상적인 지원자는 영업 경력이 있을 것이다." },
  { day: 1, w: "compensation", pos: "n.", ko: "보상, 급여", ex: "Compensation will depend on experience.", exKo: "급여는 경력에 따라 결정된다." },
  { day: 1, w: "contract", pos: "n.", ko: "계약(서)", ex: "Please sign the contract and return it by Monday.", exKo: "계약서에 서명해 월요일까지 돌려주세요." },
  { day: 1, w: "cover letter", pos: "n.", ko: "자기소개서", ex: "A cover letter should be no longer than one page.", exKo: "자기소개서는 한 페이지를 넘지 않아야 한다." },
  { day: 1, w: "deadline", pos: "n.", ko: "마감 기한", ex: "The deadline for applications is May 31.", exKo: "지원 마감일은 5월 31일이다." },
  { day: 1, w: "decline", pos: "v.", ko: "거절하다; 감소하다", ex: "He had to decline the job offer.", exKo: "그는 일자리 제안을 거절해야 했다." },
  { day: 1, w: "department", pos: "n.", ko: "부서", ex: "She works in the accounting department.", exKo: "그녀는 회계 부서에서 일한다." },
  { day: 1, w: "eligible", pos: "adj.", ko: "자격이 있는", ex: "Employees are eligible for paid leave after six months.", exKo: "직원은 6개월 후 유급 휴가를 받을 자격이 생긴다." },
  { day: 1, w: "employ", pos: "v.", ko: "고용하다", ex: "The factory will employ 200 local workers.", exKo: "그 공장은 지역 근로자 200명을 고용할 것이다." },
  { day: 1, w: "employee", pos: "n.", ko: "직원", ex: "Every new employee receives a staff ID card.", exKo: "모든 신입 직원은 사원증을 받는다." },
  { day: 1, w: "employer", pos: "n.", ko: "고용주", ex: "Your employer must provide a safe workplace.", exKo: "고용주는 안전한 작업장을 제공해야 한다." },
  { day: 1, w: "employment", pos: "n.", ko: "고용, 취업", ex: "The job fair helps graduates find employment.", exKo: "채용 박람회는 졸업생의 취업을 돕는다." },
  { day: 1, w: "enclose", pos: "v.", ko: "동봉하다", ex: "Please enclose a copy of your certificate.", exKo: "자격증 사본을 동봉해 주세요." },
  { day: 1, w: "experience", pos: "n.", ko: "경험, 경력", ex: "The position requires three years of experience.", exKo: "그 직책은 3년 경력을 요구한다." },
  { day: 1, w: "experienced", pos: "adj.", ko: "경험 많은, 숙련된", ex: "We are looking for an experienced accountant.", exKo: "숙련된 회계사를 찾고 있다." },
  { day: 1, w: "fill", pos: "v.", ko: "(자리를) 채우다, 충원하다", ex: "We hope to fill the vacancy by next week.", exKo: "다음 주까지 공석을 충원하기를 바란다." },
  { day: 1, w: "hire", pos: "v.", ko: "고용하다", ex: "The store will hire extra staff for the holidays.", exKo: "그 가게는 연휴 기간에 추가 직원을 고용할 것이다." },
  { day: 1, w: "human resources", pos: "n.", ko: "인사부, 인적 자원", ex: "Send your questions to human resources.", exKo: "질문은 인사부로 보내세요." },
  { day: 1, w: "interview", pos: "n.", ko: "면접", ex: "Your interview is scheduled for 10 a.m.", exKo: "면접은 오전 10시로 잡혀 있다." },
  { day: 1, w: "interviewee", pos: "n.", ko: "면접 대상자", ex: "Each interviewee will meet two managers.", exKo: "각 면접 대상자는 매니저 두 명을 만나게 된다." },
  { day: 1, w: "interviewer", pos: "n.", ko: "면접관", ex: "The interviewer asked about my previous job.", exKo: "면접관이 내 이전 직장에 대해 물었다." },
  { day: 1, w: "negotiate", pos: "v.", ko: "협상하다", ex: "You can negotiate your salary after the offer.", exKo: "제안을 받은 후 연봉을 협상할 수 있다." },
  { day: 1, w: "offer", pos: "n.", ko: "제안", ex: "She accepted the job offer immediately.", exKo: "그녀는 일자리 제안을 즉시 받아들였다." },
  { day: 1, w: "opening", pos: "n.", ko: "공석, 빈자리", ex: "There is an opening in the sales team.", exKo: "영업팀에 공석이 하나 있다." },
  { day: 1, w: "orientation", pos: "n.", ko: "오리엔테이션, 예비 교육", ex: "New hires must attend a one-day orientation.", exKo: "신입 사원은 하루짜리 오리엔테이션에 참석해야 한다." },
  { day: 1, w: "permanent", pos: "adj.", ko: "정규의, 영구적인", ex: "After the trial period, she got a permanent position.", exKo: "시용 기간 후 그녀는 정규직이 되었다." },
  { day: 1, w: "personnel", pos: "n.", ko: "직원들, 인사과", ex: "All personnel must wear safety helmets.", exKo: "모든 직원은 안전모를 착용해야 한다." },
  { day: 1, w: "position", pos: "n.", ko: "직책, 일자리", ex: "He applied for a position at the bank.", exKo: "그는 은행의 한 직책에 지원했다." },
  { day: 1, w: "probation", pos: "n.", ko: "수습 기간", ex: "New staff are on probation for three months.", exKo: "신입 직원은 3개월간 수습 기간을 거친다." },
  { day: 1, w: "promote", pos: "v.", ko: "승진시키다; 홍보하다", ex: "The company plans to promote her to team leader.", exKo: "회사는 그녀를 팀장으로 승진시킬 계획이다." },
  { day: 1, w: "promotion", pos: "n.", ko: "승진; 판촉", ex: "He received a promotion after two years.", exKo: "그는 2년 후 승진했다." },
  { day: 1, w: "qualification", pos: "n.", ko: "자격 (요건)", ex: "A degree in finance is the minimum qualification.", exKo: "재무 학위가 최소 자격 요건이다." },
  { day: 1, w: "qualified", pos: "adj.", ko: "자격을 갖춘", ex: "Only qualified applicants will be contacted.", exKo: "자격을 갖춘 지원자에게만 연락한다." },
  { day: 1, w: "recommendation", pos: "n.", ko: "추천(서)", ex: "Please include a letter of recommendation.", exKo: "추천서를 포함해 주세요." },
  { day: 1, w: "recruit", pos: "v.", ko: "모집하다, 채용하다", ex: "We plan to recruit ten engineers this year.", exKo: "올해 엔지니어 10명을 채용할 계획이다." },
  { day: 1, w: "reference", pos: "n.", ko: "추천인, 추천서; 참고", ex: "Please provide the name of one reference.", exKo: "추천인 한 명의 이름을 적어 주세요." },
  { day: 1, w: "require", pos: "v.", ko: "요구하다, 필요로 하다", ex: "All positions require basic computer skills.", exKo: "모든 직책은 기본 컴퓨터 능력을 요구한다." },
  { day: 1, w: "requirement", pos: "n.", ko: "요건, 필요조건", ex: "Fluency in English is a requirement for this job.", exKo: "영어 능통은 이 일의 필수 요건이다." },
  { day: 1, w: "resign", pos: "v.", ko: "사임하다, 사직하다", ex: "He will resign from his post next month.", exKo: "그는 다음 달 직책에서 사임할 것이다." },
  { day: 1, w: "resume", pos: "n.", ko: "이력서", ex: "Send your resume to the address below.", exKo: "이력서를 아래 주소로 보내세요." },
  { day: 1, w: "salary", pos: "n.", ko: "급여, 연봉", ex: "The starting salary is competitive.", exKo: "초봉은 경쟁력 있는 수준이다." },
  { day: 1, w: "screen", pos: "v.", ko: "(지원자를) 심사하다, 선별하다", ex: "The HR team will screen all applications first.", exKo: "인사팀이 먼저 모든 지원서를 심사한다." },
  { day: 1, w: "seek", pos: "v.", ko: "찾다, 구하다", ex: "We seek a motivated person to join our team.", exKo: "우리 팀에 합류할 의욕 있는 사람을 찾고 있다." },
  { day: 1, w: "submit", pos: "v.", ko: "제출하다", ex: "Please submit your documents by Friday.", exKo: "금요일까지 서류를 제출해 주세요." },

  // ── Day 1 · ★★★ 보충 12 ──
  { day: 1, w: "credentials", pos: "n.", ko: "자격 증명(서), 자격", ex: "Please bring your academic credentials to the interview.", exKo: "면접에 학력 증명서를 가져오세요." },
  { day: 1, w: "discretion", pos: "n.", ko: "재량, 신중함", ex: "Bonuses are paid at the manager's discretion.", exKo: "보너스는 관리자 재량으로 지급된다." },
  { day: 1, w: "mandatory", pos: "adj.", ko: "의무적인, 필수의", ex: "Attendance at the safety training is mandatory.", exKo: "안전 교육 참석은 의무다." },
  { day: 1, w: "prerequisite", pos: "n.", ko: "필수 조건, 전제 조건", ex: "A driver's license is a prerequisite for this job.", exKo: "운전면허는 이 일의 필수 조건이다." },
  { day: 1, w: "proficiency", pos: "n.", ko: "능숙함, 숙달", ex: "Proficiency in Excel is required.", exKo: "엑셀 능숙도가 요구된다." },
  { day: 1, w: "proficient", pos: "adj.", ko: "능숙한", ex: "Applicants must be proficient in Spanish.", exKo: "지원자는 스페인어에 능숙해야 한다." },
  { day: 1, w: "prospective", pos: "adj.", ko: "장래의, 예비의", ex: "We met with several prospective employees.", exKo: "여러 예비 직원들과 만났다." },
  { day: 1, w: "retain", pos: "v.", ko: "보유하다, 유지하다", ex: "The company works hard to retain skilled workers.", exKo: "회사는 숙련된 직원을 붙잡아 두려고 노력한다." },
  { day: 1, w: "retention", pos: "n.", ko: "보유, (직원) 유지", ex: "Employee retention improved after the pay raise.", exKo: "임금 인상 후 직원 유지율이 개선됐다." },
  { day: 1, w: "solicit", pos: "v.", ko: "요청하다, 구하다", ex: "The manager will solicit feedback from staff.", exKo: "매니저가 직원들에게 의견을 요청할 것이다." },
  { day: 1, w: "terminate", pos: "v.", ko: "종료하다, 해고하다", ex: "Either party may terminate the contract with notice.", exKo: "어느 쪽이든 통지 후 계약을 종료할 수 있다." },
  { day: 1, w: "termination", pos: "n.", ko: "종료, 해고", ex: "Termination of the lease requires 30 days' notice.", exKo: "임대 계약 해지에는 30일 전 통지가 필요하다." },
];
